<?php
/**
 * Consent
 *
 * PHP version 5
 *
 * @category Class
 * @package  GoDaddyDomainsClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace GoDaddyDomainsClient\Model;

use \ArrayAccess;

/**
 * Consent Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     GoDaddyDomainsClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Consent implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Consent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'agreement_keys' => 'string[]',
        'agreed_by' => 'string',
        'agreed_at' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'agreement_keys' => 'agreementKeys',
        'agreed_by' => 'agreedBy',
        'agreed_at' => 'agreedAt'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'agreement_keys' => 'setAgreementKeys',
        'agreed_by' => 'setAgreedBy',
        'agreed_at' => 'setAgreedAt'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'agreement_keys' => 'getAgreementKeys',
        'agreed_by' => 'getAgreedBy',
        'agreed_at' => 'getAgreedAt'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['agreement_keys'] = isset($data['agreement_keys']) ? $data['agreement_keys'] : null;
        $this->container['agreed_by'] = isset($data['agreed_by']) ? $data['agreed_by'] : null;
        $this->container['agreed_at'] = isset($data['agreed_at']) ? $data['agreed_at'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['agreement_keys'] === null) {
            $invalid_properties[] = "'agreement_keys' can't be null";
        }
        if ($this->container['agreed_by'] === null) {
            $invalid_properties[] = "'agreed_by' can't be null";
        }
        if ($this->container['agreed_at'] === null) {
            $invalid_properties[] = "'agreed_at' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['agreement_keys'] === null) {
            return false;
        }
        if ($this->container['agreed_by'] === null) {
            return false;
        }
        if ($this->container['agreed_at'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets agreement_keys
     * @return string[]
     */
    public function getAgreementKeys()
    {
        return $this->container['agreement_keys'];
    }

    /**
     * Sets agreement_keys
     * @param string[] $agreement_keys Unique identifiers of the legal agreements to which the end-user has agreed, as returned from the/domains/agreements endpoint
     * @return $this
     */
    public function setAgreementKeys($agreement_keys)
    {
        $this->container['agreement_keys'] = $agreement_keys;

        return $this;
    }

    /**
     * Gets agreed_by
     * @return string
     */
    public function getAgreedBy()
    {
        return $this->container['agreed_by'];
    }

    /**
     * Sets agreed_by
     * @param string $agreed_by Originating client IP address of the end-user's computer when they consented to these legal agreements
     * @return $this
     */
    public function setAgreedBy($agreed_by)
    {
        $this->container['agreed_by'] = $agreed_by;

        return $this;
    }

    /**
     * Gets agreed_at
     * @return string
     */
    public function getAgreedAt()
    {
        return $this->container['agreed_at'];
    }

    /**
     * Sets agreed_at
     * @param string $agreed_at Timestamp indicating when the end-user consented to these legal agreements
     * @return $this
     */
    public function setAgreedAt($agreed_at)
    {
        $this->container['agreed_at'] = $agreed_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\GoDaddyDomainsClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\GoDaddyDomainsClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


